version: "3.3"
volumes:
  php-fpm-socket:
  db_data:
networks:
  app_net:
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    networks:
      - app_net

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${WEB_PORT:-85}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    networks:
      - app_net

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "8001:80"
    networks:
      - app_net